server:
  port: 16384

spring:
  datasource:
    url: jdbc:mysql://rinne.top:3306/student_admin?useUnicode=true&characterEncoding=UTF-8
    username: student_admin
    password: 12345aaaa
    driver-class-name: com.mysql.cj.jdbc.Driver

  resources:
    static-locations: classpath:static/

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: pers.rinne.studentadmin.bean